def execute(block)
  block.call
end

execute { puts "Hello from inside the execute method!" }

Give us the following error when we run it?

block.rb1:in `execute': wrong number of arguments (0 for 1) (ArgumentError)
from test.rb:5:in `<main>'

ANSWER:
In the method definition, (block) is a parameter which the error is saying it's missing from the call. (Otherwise known as an argument.) To make this work, (block) needs to be (&block).